kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-configmap
  namespace: monitor
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.mail.me.com:587'
      smtp_from: 'wang_chunyi@icloud.com'
      smtp_auth_username: 'wang_chunyi@icloud.com'
      smtp_auth_password: 'know-ayks-lkff-oumb'
      smtp_require_tls: true
    templates:
      - '/template/*.tmpl'
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: email
    receivers:
    - name: 'email'
      email_configs:
      - to: 'wang_chunyi@icloud.com'
        headers: { Subject: " WARNING- -告警邮件" }
        send_resolved: true
        html: '{{ template "email.to.html" . }}'
    inhibit_rules:
      - source_match:
          severity: 'high'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance', 'job']
  
  email.tmpl: |-
    {{ define "email.to.html" }}
    {{- if gt (len .Alerts.Firing) 0 -}}
      {{- range $index, $alert := .Alerts -}}
        {{- if true }}
          ========= 异常告警========== <br>
          告警程序: prometheus_alert <br>
          告警级别: {{ .Labels.severity }} 级<br>
          告警状态: {{ .Status }} <br>
          告警类型: {{ .Labels.alertname }} <br>
          故障主机: {{ .Labels.instance }} <br>
          告警主题: {{ .Annotations.summary }} <br>
          主题内容: {{ .Annotations.description }} <br>
          value: {{ .Annotations.value }} <br>
          故障时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }} <br>
          ========= end ========== <br>
        {{- end }}
      {{- end }}
    {{- end }}

    {{- if gt (len .Alerts.Resolved) 0 -}}
      {{- range $index, $alert := .Alerts -}}
        {{- if true }}
          ========= 异常恢复========== <br>
          告警程序: prometheus_alert <br>
          告警级别: {{ .Labels.severity }} 级<br>
          告警状态: {{ .Status }} <br>
          告警类型: {{ .Labels.alertname }} <br>
          故障主机: {{ .Labels.instance }} <br>
          告警主题: {{ .Annotations.summary }} <br>
          主题内容: {{ .Annotations.description }} <br>
          value: {{ .Annotations.value }} <br>
          故障时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }} <br>
          恢复时间: {{ (.EndsAt.Add 28800e9).Format "2006-01-02 15:04:05" }} <br>
          ========= end ========== <br>
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}