kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus-config
  namespace: monitor
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 1m
      
    scrape_configs:
      - job_name: 'kube-state-metrics'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: http
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_service_name
          - __meta_kubernetes_endpoint_port_name
          action: keep
          regex: kube-system;kube-state-metrics;http-metrics
      - job_name: 'kube-state-metrics-self'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: http
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_service_name
          - __meta_kubernetes_endpoint_port_name
          action: keep
          regex: kube-system;kube-state-metrics;telemetry
      - job_name: 'kubernetes-apiserver'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        authorization:
          credentials_file:
            /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_service_name
          - __meta_kubernetes_endpoint_port_name
          action: keep
          regex: default;kubernetes;https
      - job_name: 'kubernetes-kubelet'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      - job_name: 'kubernetes-cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: 
          - __meta_kubernetes_node_name
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

      # Node exporter 监控
      - job_name: 'node-exporter-kubernetes'
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - source_labels: 
          - __address__
          regex: '(.*):10250'
          replacement: '${1}:9100'
          target_label: __address__
          action: replace
        - source_labels: # 将节点名称作为node标签
          - __meta_kubernetes_node_name
          target_label: node
        - action: labelmap # 将kubernetes 节点标签映射为prometheus target标签
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: node_type
          replacement: kubernetes
          
      # - job_name: 'node-exporter-kubernetes'
      #   kubernetes_sd_configs:
      #   - role: pod
      #     namespaces:
      #       names: ['monitor']
      #   relabel_configs:
      #   # 过滤 app: node-exporter 的 Pod
      #   - source_labels: [__meta_kubernetes_pod_label_app]
      #     action: keep
      #     regex: node-exporter
      #   # 过滤 9100 端口
      #   - source_labels: [__meta_kubernetes_pod_container_port_number]
      #     action: keep
      #     regex: '9100'
      #   # 使用 Pod 的node_name 所在节点作为 node 标签
      #   - source_labels: [__meta_kubernetes_pod_node_name]
      #     target_label: node
      #   # 标记节点类型
      #   - target_label: node_type
      #     replacement: kubernetes

        # 将非kubernetes节点的vm加入监控
      - job_name: 'node-exporter-vm'
        static_configs:
        - targets: 
          - "192.168.100.31:9100"
          labels: # 声明节点类型和名称(用hostname)
            node: nfs-31
            node_type: vm

      # 埋点数据监控
      - job_name: 'kubernetes-endpoints'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: 
            - __meta_kubernetes_service_annotation_prometheus_io_scrape
          action: keep
          regex: true
        - source_labels: 
            - __meta_kubernetes_service_annotation_prometheus_io_scheme
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: 
            - __meta_kubernetes_service_annotation_prometheus_io_path
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: 
            - __address__
            - __meta_kubernetes_service_annotation_prometheus_io_port
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: 
            - __meta_kubernetes_namespace
          action: replace
          target_label: kubernetes_namespace
        - source_labels: 
            - __meta_kubernetes_service_name
          action: replace
          target_label: kubernetes_name
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
          - source_labels: 
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            action: keep
            regex: true
          - source_labels: 
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: 
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: 
              - __meta_kubernetes_namespace
            action: replace
            target_label: kubernetes_namespace
          - source_labels: 
              - __meta_kubernetes_pod_name
            action: replace
            target_label: kubernetes_pod_name
      # Etcd监控
      - job_name: 'kubernetes-etcd'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/k8s-certs/etcd/ca.crt
          cert_file: /var/run/secrets/kubernetes.io/k8s-certs/etcd/server.crt
          key_file: /var/run/secrets/kubernetes.io/k8s-certs/etcd/server.key
        scrape_interval: 5s
        static_configs:
        - targets: ['192.168.100.5:2379']
      # 监控证书有效期
      - job_name: 'node-cert-exporter'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names: ['monitor']
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: node-cert-exporter
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: '9117'
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node

      # Ingress监控
      - job_name: 'kubernetes-ingress'
        scheme: http
        scrape_interval: 5s
        static_configs:
        - targets: 
          - '192.168.100.6:10254'
          - '192.168.100.7:10254'

      - job_name: 'Alertmanager'
        static_configs:
        - targets:
          - alertmanager.monitor.svc.cluster.local:9093
      # Push Gateway 监控
      - job_name: 'pushgateway'
        honor_labels: true
        static_configs:
        - targets:
          - pushgateway.monitor.svc.cluster.local:9091

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager.monitor.svc.cluster.local:9093
    rule_files:
      - '/rules/*_rules.yml'
  
  # node-exporter_rules.yml: |
  #   groups:
  #   - name: node-exporter_rules
  #     rules:
  #     - alert: NodeExporterDown
  #       expr: up{job=~"kubernetes-nodes-exporter|nfs-node"} == 0
  #       for: 1m
  #       labels:
  #         severity: high
  #       annotations:
  #         summary: "Node {{ $labels.instance }} down"
  #         description: "The node {{ $labels.instance }} has been down for more than 1 minute."
