apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: monitor
  labels:
    app: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: monitor
      containers:
      - name: prometheus
        image: prom/prometheus:v2.37.8
        imagePullPolicy: IfNotPresent
        command:
          - prometheus
          - --config.file=/etc/prometheus/prometheus.yml
          - --storage.tsdb.path=/prometheus
          - --storage.tsdb.retention=720h
          - --web.enable-lifecycle
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        # Alert Manager 告警规则配置文件
        # - name: node-exporter-rules
        #   mountPath: /rules/node-exporter/
        # - name: node-resources-rules
        #   mountPath: /rules/node-resources/
        - name: prometheus-storage-volume
          mountPath: /prometheus/
        - name: etcd-certs
          mountPath: /var/run/secrets/kubernetes.io/k8s-certs/etcd/
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: prometheus-config
        configMap:
          name: prometheus-config
          items:
            - key: prometheus.yml
              path: prometheus.yml
              mode: 0644
      - name: prometheus-storage-volume
        persistentVolumeClaim:
          claimName: prometheus-pvc
      - name: etcd-certs
        secret:
          secretName: etcd-certs
      # - name: node-exporter-rules
      #   configMap:
      #     name: node-exporter-rules
      # - name: node-resources-rules
      #   configMap:
      #     name: node-resources-rules

