apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor
  namespace: monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-clusterrolebinding
  namespace: monitor
subjects:
- name: monitor
  namespace: monitor
  kind: ServiceAccount
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
