---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-eagle-mysql-pvc
  namespace: logging
  labels:
    app.kubernetes.io/instance: kafka-eagle-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-eagle-mysql
  namespace: logging
spec:
  selector:
    matchLabels:
      app: kafka-eagle-mysql
  template:
    metadata:
      labels:
        app: kafka-eagle-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: kafka-eagle-mysql
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        env:
        # 数据库密码
        - name: MYSQL_ROOT_PASSWORD
          value: zz123..
        - name: MYSQL_DATABASE
          value: kafka
        - name: MYSQL_USER
          value: kafkaeagle
        - name: MYSQL_PASSWORD
          value: kafkaeagle123..
        ports:
        - name: tcp-3306
          containerPort: 3306
        volumeMounts:
        - name: host-time
          readOnly: true
          mountPath: /etc/localtime
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: mysql-data
        persistentVolumeClaim:
          claimName: kafka-eagle-mysql-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-eagle-mysql-svc
  namespace: logging
spec:
  clusterIP: None
  selector:
    app: kafka-eagle-mysql
  ports:
  - name: tcp
    port: 3306
    targetPort: 3306