apiVersion: v1
kind: Service
metadata:
  name: kafka-eagle
  namespace: logging
spec:
  type: NodePort
  ports:
  - port: 8048
    targetPort: 8048
    nodePort: 30048
  selector:
    app: kafka-eagle